# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.utils.timezone
import phonenumber_field.modelfields
import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gender', 'Gender'), ('religion', 'Religion'), ('mother_tongue', 'Mother Tongue'), ('nationality', 'Nationality'), ('blood_group', 'Blood Group'), ('special_needs', 'Special Needs'), ('emergency_relationship', 'Emergency Relationship'), ('father_status', 'Father Status'), ('mother_status', 'Mother Status'), ('marital_status', 'Marital Status'), ('shift', 'Shift'), ('section', 'Section')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('name', models.CharField(help_text="Student's full name", max_length=200, validators=[students.validators.StudentValidator.validate_name])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of birth (student must be 3-25 years old)', null=True, validators=[students.validators.StudentValidator.validate_date_of_birth])),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=100, null=True)),
                ('student_cnic', models.CharField(blank=True, help_text="Student's B-Form / CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('special_needs_disability', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text="Student's email address (optional)", max_length=254, null=True)),
                ('country_code', models.CharField(blank=True, help_text='Default country code (e.g. +92)', max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Student's phone number", max_length=128, null=True, region=None)),
                ('emergency_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Emergency contact number', max_length=128, null=True, region=None)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_cnic', models.CharField(blank=True, help_text="Father's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('father_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Father's contact number", max_length=128, null=True, region=None)),
                ('father_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_cnic', models.CharField(blank=True, help_text="Guardian's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('guardian_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Guardian's contact number", max_length=128, null=True, region=None)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_cnic', models.CharField(blank=True, help_text="Mother's CNIC (13 digits)", max_length=20, null=True, validators=[students.validators.StudentValidator.validate_cnic])),
                ('mother_status', models.CharField(blank=True, choices=[('widowed', 'Widowed'), ('divorced', 'Divorced'), ('married', 'Married')], max_length=20, null=True)),
                ('mother_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Mother's contact number", max_length=128, null=True, region=None)),
                ('mother_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, help_text='Complete address (10-500 characters)', null=True, validators=[students.validators.StudentValidator.validate_address])),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly family income in PKR', max_digits=10, null=True, validators=[students.validators.StudentValidator.validate_positive_number])),
                ('house_owned', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Is the house owned by the family?', max_length=10, null=True)),
                ('zakat_status', models.CharField(blank=True, choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable')], help_text='Zakat eligibility status', max_length=20, null=True)),
                ('terminated_on', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('last_class_teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('old_gr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('siblings_count', models.PositiveIntegerField(blank=True, help_text='Number of siblings (positive integer)', null=True)),
                ('father_status', models.CharField(blank=True, choices=[('alive', 'Alive'), ('dead', 'Dead')], max_length=20, null=True)),
                ('gr_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('student_code', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('enrollment_year', models.IntegerField(blank=True, help_text='Year of enrollment (2000-2030)', null=True, validators=[students.validators.StudentValidator.validate_year])),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text="Student's shift", max_length=20, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Active students appear in attendance sheets and class lists')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dynamic_data', models.JSONField(blank=True, default=dict, help_text='Stores extra dynamic form data', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
