# Generated by Django 5.2.12 on 2026-04-23 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0002_initial'),
        ('students', '0003_remove_student_unique_active_student_email_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_active_student_code',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'student_id'), name='unique_active_student_id_per_org'),
        ),
    ]
