# Generated by Django 5.2.14 on 2026-06-08 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0003_grade_order'),
        ('students', '0004_remove_student_unique_active_student_code_and_more'),
        ('users', '0009_merge_0005_remove_git_commit_0008_merge_20260515_0653'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_deleted'], name='idx_student_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_deleted', 'is_active'], name='idx_student_deleted_active'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'is_deleted'], name='idx_student_org_deleted'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['campus', 'is_deleted'], name='idx_student_campus_deleted'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classroom', 'is_deleted'], name='idx_student_classroom_deleted'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_grade', 'is_deleted'], name='idx_student_grade_deleted'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='idx_student_org_active_deleted'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-created_at'], name='idx_student_created_at'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='idx_student_student_id'),
        ),
    ]
