# Generated by Django 5.2.14 on 2026-07-02 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_student_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('left', 'Left'), ('re_enrolled', 'Re-enrolled'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], db_index=True, default='enrolled', help_text='Lifecycle status. Change only via change_status() so the event log stays in sync.', max_length=20),
        ),
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enrolled', 'Enrolled'), ('left', 'Left'), ('re_enrolled', 'Re-enrolled'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], max_length=20)),
                ('event_date', models.DateField(help_text='Date the change actually took effect')),
                ('reason', models.TextField(blank=True, help_text="Required for 'left' / 'transferred'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_events_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_events', to='students.student')),
            ],
            options={
                'ordering': ['event_date', 'created_at'],
                'indexes': [models.Index(fields=['student', 'event_date'], name='students_en_student_4320c3_idx'), models.Index(fields=['event_type', 'event_date'], name='students_en_event_t_ab525e_idx')],
            },
        ),
    ]
