# Generated by Django 5.2.14 on 2026-06-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_student_performance_indexes'),
        ('students', '0006_remove_student_last_class_passed'),
    ]

    operations = [
    ]
