# Generated by Django 5.2.15 on 2026-07-04 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_backfill_enrollment_status'),
        ('users', '0010_alter_rolepermission_permission_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('left', 'Left'), ('re_enrolled', 'Re-enrolled'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], max_length=20)),
                ('event_date', models.DateField(help_text='Date the change should take effect')),
                ('reason', models.TextField(blank=True, help_text='Why the change is needed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('coordinator_response', models.TextField(blank=True, help_text="Coordinator's note on approve/reject", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_status_requests', to='users.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_status_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_status_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_status_requests', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='students_en_status_39c8f5_idx'), models.Index(fields=['student', 'status'], name='students_en_student_4458b5_idx')],
            },
        ),
    ]
