# Generated by Django 5.2.15 on 2026-07-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_backfill_enrollment_status'),
        ('students', '0007_merge_20260609_1023'),
    ]

    operations = [
    ]
