# Generated by Django 5.2.15 on 2026-07-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_grade_order'),
        ('students', '0008_enrollmentstatusrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom the student had before going inactive (left/transferred)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_students', to='classes.classroom'),
        ),
    ]
