# Generated by Django 5.2.15 on 2026-07-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_merge_20260702_1228'),
        ('students', '0009_student_last_classroom'),
    ]

    operations = [
    ]
