# Generated by Django 5.2.15 on 2026-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_last_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentevent',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('dropout', 'Dropout'), ('transferred_out', 'Transferred Out'), ('graduated', 'Graduated'), ('other', 'Other')], db_index=True, help_text='Structured exit reason (dropout / transferred_out / graduated / other)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentstatusrequest',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('dropout', 'Dropout'), ('transferred_out', 'Transferred Out'), ('graduated', 'Graduated'), ('other', 'Other')], help_text="Structured exit reason (required when requesting 'left')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentevent',
            name='reason',
            field=models.TextField(blank=True, help_text="Free-text detail (required for 'left' / 'transferred')"),
        ),
    ]
