# Generated by Django 5.2.15 on 2026-07-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0003_grade_order'),
        ('students', '0010_enrollmentevent_reason_code_and_more'),
        ('users', '0010_alter_rolepermission_permission_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(db_index=True, max_length=20)),
                ('snapshot_type', models.CharField(choices=[('start_of_year', 'Start of Year'), ('end_of_year', 'End of Year'), ('promotion', 'Promotion')], default='start_of_year', max_length=20)),
                ('snapshot_date', models.DateField()),
                ('grade', models.CharField(blank=True, help_text='current_grade at snapshot time', max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('left', 'Left'), ('re_enrolled', 'Re-enrolled'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classroom')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_snapshots', to='users.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_snapshots', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['academic_year', 'snapshot_type'], name='students_en_academi_5aa08a_idx'), models.Index(fields=['student', 'academic_year'], name='students_en_student_8f2aee_idx')],
                'unique_together': {('student', 'academic_year', 'snapshot_type')},
            },
        ),
    ]
