# Generated by Django 5.2.15 on 2026-07-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_merge_20260704_1146'),
        ('students', '0011_enrollmentsnapshot'),
    ]

    operations = [
    ]
