# Generated by Django 5.2.15 on 2026-07-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_enrollmentsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_class_passed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
