# Generated by Django 5.2.15 on 2026-07-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_merge_20260708_1020'),
        ('students', '0012_student_last_class_passed'),
    ]

    operations = [
    ]
