# Generated by Django 5.2.15 on 2026-07-09 12:08

from django.db import migrations


class Migration(migrations.Migration):
    """No-op. Kept so the recorded migration history stays intact.

    This was generated during a branch merge and re-added `last_class_passed`,
    which 0012_student_last_class_passed already adds. Because 0013 depends on
    0012, that column always exists by the time this runs, so the original
    AddField could never succeed on a fresh database — it only survived here by
    being faked. Removing the operation lets `migrate` run from scratch, which
    tests and CI need.
    """

    dependencies = [
        ('students', '0013_merge_20260709_1203'),
    ]

    operations = []
