"use client"

import { useEffect, useState, useRef } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { AlertCircle, Loader2, CheckCircle, Wand2, Pencil } from "lucide-react"
import { getApiBaseUrl } from "@/lib/api"
import { formatCnicDashed, parseField, sanitizeEmail } from "@/lib/validation/common"
import { staffCnicField, staffContactNumberField, staffEmailField } from "@/lib/validation/schemas/_staffShared"
import { getCountries, getCountryCallingCode } from "libphonenumber-js"
import { DatePicker } from "@/components/ui/date-picker"

interface PersonalInfoStepProps {
  formData: any
  invalidFields: string[]
  onInputChange: (field: string, value: any) => void
  fieldErrors: Record<string, string>
  setFieldErrors: (errors: Record<string, string> | ((prev: Record<string, string>) => Record<string, string>)) => void
  isValidating: Record<string, boolean>
  setIsValidating: (validating: Record<string, boolean> | ((prev: Record<string, boolean>) => Record<string, boolean>)) => void
  formOptions?: any
}

const countryCodesList = (() => {
  try {
    const regionNames = new Intl.DisplayNames(['en'], { type: 'region' });
    const getFlagEmoji = (countryCode: string) => {
      return countryCode
        .toUpperCase()
        .replace(/./g, char => String.fromCodePoint(127397 + char.charCodeAt(0)));
    };

    return getCountries()
      .map(country => ({
        label: `${getFlagEmoji(country)} ${regionNames.of(country)} (+${getCountryCallingCode(country)})`,
        value: `+${getCountryCallingCode(country)}`,
        iso: country
      }))
      .sort((a, b) => a.label.localeCompare(b.label));
  } catch (e) {
    return [
      { label: "🇵🇰 Pakistan (+92)", value: "+92", iso: "PK" },
      { label: "🇺🇸 United States (+1)", value: "+1", iso: "US" },
    ];
  }
})();

// --- Teacher ID Field (Auto / Manual Toggle) ---
function TeacherIdField({ formData, onInputChange }: { formData: any; onInputChange: (f: string, v: string) => void }) {
  const [manual, setManual] = useState(!!formData.teacher_id)

  const switchToManual = () => {
    setManual(true)
    onInputChange("teacher_id", "")
  }

  const switchToAuto = () => {
    setManual(false)
    onInputChange("teacher_id", "")
  }

  return (
    <div className="mb-4">
      <div className="flex items-center justify-between mb-1.5">
        <Label htmlFor="teacher_id" className="font-semibold text-gray-700">Teacher ID / Employee Code</Label>
        <button
          type="button"
          onClick={manual ? switchToAuto : switchToManual}
          className={`flex items-center gap-1.5 text-[11px] font-bold px-3 py-1 rounded-full border transition-all duration-200 shadow-sm ${
            manual
              ? "bg-amber-50 border-amber-300 text-amber-700 hover:bg-amber-100"
              : "bg-blue-50 border-blue-300 text-blue-700 hover:bg-blue-100"
          }`}
        >
          {manual ? (
            <><Wand2 className="h-3.5 w-3.5" /> Switch to Auto-generate</>
          ) : (
            <><Pencil className="h-3.5 w-3.5" /> Enter ID Manually</>
          )}
        </button>
      </div>

      {manual ? (
        <Input
          id="teacher_id"
          value={formData.teacher_id || ""}
          onChange={(e) => onInputChange("teacher_id", e.target.value)}
          placeholder="e.g. TEA-2025-001"
          className="border-2 focus:border-blue-400 rounded-xl h-11"
        />
      ) : (
        <Input
          id="teacher_id"
          value=""
          readOnly
          placeholder="Will be auto-generated by system"
          className="bg-gray-50 text-gray-400 italic cursor-not-allowed border-dashed border-2 rounded-xl h-11"
        />
      )}
      <p className="text-[10px] text-gray-400 mt-1.5 px-1">
        {manual
          ? "⚠️ Manual ID entry. Ensure it is unique to avoid submission errors."
          : "ℹ️ System will automatically assign a unique code based on Campus and Join Date."}
      </p>
    </div>
  )
}

// --- Phone Input with Country Code ---
const PhoneInputWithCode = ({ 
    id, 
    label, 
    value, 
    required = false, 
    error,
    isValidating,
    onChange 
  }: { 
    id: string, 
    label: string, 
    value: string, 
    required?: boolean,
    error?: string,
    isValidating?: boolean,
    onChange: (val: string) => void 
  }) => {
    const parts = (value || "").split(" ")
    const currentCode = parts.length > 1 ? parts[0] : "+92"
    const currentNum = parts.length > 1 ? parts[1] : (value || "").replace(/^\+\d+\s?/, "")
  
    const handleCodeChange = (code: string) => {
      onChange(`${code} ${currentNum}`)
    }
  
    const handleNumChange = (num: string) => {
      let cleanNum = num.replace(/\D/g, '')
      if (cleanNum.startsWith('0')) {
        cleanNum = cleanNum.substring(1)
      }
      cleanNum = cleanNum.slice(0, 11)
      onChange(`${currentCode} ${cleanNum}`)
    }
  
    return (
      <div className="space-y-2">
        <Label htmlFor={id} className="font-semibold text-gray-700">{label} {required && "*"}</Label>
        <div className="flex gap-2">
          <Select value={currentCode} onValueChange={handleCodeChange}>
            <SelectTrigger className="w-[110px] border-2 rounded-xl h-11 focus:ring-blue-400">
              <SelectValue>{currentCode || "+92"}</SelectValue>
            </SelectTrigger>
            <SelectContent className="max-h-[300px] rounded-xl">
              {countryCodesList.map((c: any) => (
                <SelectItem key={`${c.iso}-${c.value}`} value={c.value} className="py-2.5">{c.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Input
            id={id}
            value={currentNum}
            onChange={(e) => handleNumChange(e.target.value)}
            className={`flex-1 border-2 rounded-xl h-11 focus:border-blue-400 ${error ? "border-red-500" : ""}`}
            placeholder="3XX-XXXXXXX"
            maxLength={11}
          />
        </div>
        {error && (
          <p className="text-sm text-red-500 flex items-center gap-1 mt-1">
            <AlertCircle className="h-4 w-4" />
            {error}
          </p>
        )}
        {isValidating && (
          <p className="text-sm text-blue-500 flex items-center gap-1 mt-1 animate-pulse">
            <Loader2 className="h-4 w-4 animate-spin" />
            Validating...
          </p>
        )}
      </div>
    )
}

export function PersonalInfoStep({ 
  formData, 
  invalidFields, 
  onInputChange, 
  fieldErrors, 
  setFieldErrors, 
  isValidating, 
  setIsValidating,
  formOptions 
}: PersonalInfoStepProps) {
  const validationTimeouts = useRef<Record<string, NodeJS.Timeout>>({})

  // uniqueness checks
  const checkEmailUniqueness = async (email: string): Promise<{ isUnique: boolean; message: string }> => {
    try {
      const base = getApiBaseUrl()
      const cleanBase = base.endsWith('/') ? base.slice(0, -1) : base
      const token = localStorage.getItem('sis_access_token') || ''
      const response = await fetch(`${cleanBase}/api/teachers/check-email/?email=${encodeURIComponent(email)}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })
      if (!response.ok) return { isUnique: true, message: '' }
      const data = await response.json()
      if (data.exists) return { isUnique: false, message: 'This email is already in use by another teacher or user.' }
      return { isUnique: true, message: '' }
    } catch {
      return { isUnique: true, message: '' }
    }
  }

  const checkCNICUniqueness = async (cnic: string): Promise<{ isUnique: boolean; message: string }> => {
    try {
      const base = getApiBaseUrl()
      const cleanBase = base.endsWith('/') ? base.slice(0, -1) : base
      const token = localStorage.getItem('sis_access_token') || ''
      const cleanCNIC = cnic.replace(/\D/g, '')
      const response = await fetch(`${cleanBase}/api/teachers/check-cnic/?cnic=${cleanCNIC}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })
      if (!response.ok) return { isUnique: true, message: '' }
      const data = await response.json()
      if (data.exists) return { isUnique: false, message: 'This CNIC is already registered.' }
      return { isUnique: true, message: '' }
    } catch {
      return { isUnique: true, message: '' }
    }
  }

  const checkPhoneUniqueness = async (phone: string): Promise<{ isUnique: boolean; message: string }> => {
    try {
      const base = getApiBaseUrl()
      const cleanBase = base.endsWith('/') ? base.slice(0, -1) : base
      const token = localStorage.getItem('sis_access_token') || ''
      const encodePhone = encodeURIComponent(phone)
      const response = await fetch(`${cleanBase}/api/teachers/check-phone/?phone=${encodePhone}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })
      if (!response.ok) return { isUnique: true, message: '' }
      const data = await response.json()
      if (data.exists) return { isUnique: false, message: 'This Phone Number is already registered.' }
      return { isUnique: true, message: '' }
    } catch {
      return { isUnique: true, message: '' }
    }
  }

  const validateField = async (field: string, value: string) => {
    setIsValidating((prev) => ({ ...prev, [field]: true }))
    let error = ''

    switch (field) {
      case 'cnic':
        const cnicVal = parseField(staffCnicField(), value)
        if (!cnicVal.isValid) {
          error = cnicVal.message || ''
        } else {
          const uniq = await checkCNICUniqueness(value)
          if (!uniq.isUnique) error = uniq.message
        }
        break
      case 'email':
        const emailVal = parseField(staffEmailField(), value)
        if (!emailVal.isValid) {
          error = emailVal.message || ''
        } else {
          const uniq = await checkEmailUniqueness(value)
          if (!uniq.isUnique) error = uniq.message
        }
        break
      case 'contact_number':
        const phoneVal = parseField(staffContactNumberField(), value)
        if (!phoneVal.isValid) {
          error = phoneVal.message || ''
        } else {
          const uniq = await checkPhoneUniqueness(value)
          if (!uniq.isUnique) error = uniq.message
        }
        break
    }

    setFieldErrors((prev) => ({ ...prev, [field]: error }))
    setIsValidating((prev) => ({ ...prev, [field]: false }))
  }

  const handleInputChangeWithValidation = (field: string, value: any) => {
    let finalValue = value
    if (field === 'cnic') finalValue = formatCnicDashed(value)
    if (field === 'email') finalValue = sanitizeEmail(value)

    onInputChange(field, finalValue)
    
    if (fieldErrors[field]) {
      setFieldErrors((prev) => ({ ...prev, [field]: '' }))
    }
    
    if (validationTimeouts.current[field]) clearTimeout(validationTimeouts.current[field])
    
    if (['cnic', 'email', 'contact_number'].includes(field)) {
      validationTimeouts.current[field] = setTimeout(() => {
        validateField(field, finalValue)
      }, 500)
    }
  }

  useEffect(() => {
    return () => {
      Object.values(validationTimeouts.current).forEach(t => t && clearTimeout(t))
    }
  }, [])

  return (
    <Card className="border-2 shadow-sm rounded-3xl overflow-hidden">
      <CardHeader className="bg-gray-50/50 border-b">
        <CardTitle className="text-xl font-bold text-blue-900 flex items-center gap-2">
            <span className="h-8 w-8 rounded-lg bg-blue-600 flex items-center justify-center text-white text-base">1</span>
            Personal Information
        </CardTitle>
      </CardHeader>
      <CardContent className="p-6 space-y-6">
        
        <TeacherIdField formData={formData} onInputChange={onInputChange} />
        
        <div className="bg-violet-50/50 p-4 rounded-2xl border-2 border-violet-100 mb-6">
          <Label htmlFor="biometric_id" className="font-bold text-violet-900 flex items-center gap-2 mb-1.5">
            <span className="h-5 w-5 bg-violet-600 rounded text-white flex items-center justify-center text-[10px]">ZK</span>
            Biometric Device User ID (Optional)
          </Label>
          <Input
            id="biometric_id"
            value={formData.biometric_id || ""}
            onChange={(e) => onInputChange("biometric_id", e.target.value)}
            className="border-2 focus:border-violet-400 rounded-xl h-11 bg-white"
            placeholder="Machine User ID (e.g. 101)"
          />
          <p className="text-[10px] text-violet-500 mt-1.5 px-1 italic font-medium">
            Fingerprint machine par jo User ID hai wo yahan daalein taake attendane auto-link ho jaye.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <Label htmlFor="full_name" className="font-semibold text-gray-700">Full Name *</Label>
            <Input
              id="full_name"
              value={formData.full_name || ""}
              onChange={(e) => onInputChange("full_name", e.target.value)}
              className={`border-2 rounded-xl h-11 focus:border-blue-400 ${invalidFields.includes("full_name") ? "border-red-500" : ""}`}
              placeholder="Enter full name"
            />
            {invalidFields.includes("full_name") && <p className="text-xs text-red-500 mt-1">Full name is required</p>}
          </div>

          <div>
            <Label htmlFor="father_name" className="font-semibold text-gray-700">Father / Husband Name</Label>
            <Input
              id="father_name"
              value={formData.father_name || ""}
              onChange={(e) => onInputChange("father_name", e.target.value)}
              className="border-2 rounded-xl h-11 focus:border-blue-400"
              placeholder="Enter father or husband name"
            />
          </div>

          <div>
            <DatePicker
              id="dob"
              label="Date of Birth"
              required
              date={formData.dob}
              onChange={(v: string) => handleInputChangeWithValidation("dob", v)}
              error={invalidFields.includes("dob")}
              disabled={(date: Date) => date > new Date() || date < new Date("1900-01-01")}
            />
            {invalidFields.includes("dob") && <p className="text-xs text-red-500 mt-1 font-medium italic">Date of birth is required</p>}
          </div>

          <div>
            <Label htmlFor="gender" className="font-semibold text-gray-700">Gender *</Label>
            <Select value={formData.gender || ""} onValueChange={(v) => onInputChange("gender", v)}>
              <SelectTrigger className={`border-2 rounded-xl h-11 focus:border-blue-400 ${invalidFields.includes("gender") ? "border-red-500" : ""}`}>
                <SelectValue placeholder="Select gender" />
              </SelectTrigger>
              <SelectContent className="rounded-xl">
                {formOptions?.gender?.map((o: any) => (
                  <SelectItem key={o.value} value={o.value} className="py-2.5">{o.label}</SelectItem>
                )) || (
                  <>
                    <SelectItem value="male" className="py-2.5">Male</SelectItem>
                    <SelectItem value="female" className="py-2.5">Female</SelectItem>
                  </>
                )}
              </SelectContent>
            </Select>
            {invalidFields.includes("gender") && <p className="text-xs text-red-500 mt-1 font-medium italic">Gender is required</p>}
          </div>

          <PhoneInputWithCode
            id="contact_number"
            label="Contact Number"
            value={formData.contact_number}
            required
            error={fieldErrors.contact_number || (invalidFields.includes("contact_number") ? "Contact number is required" : "")}
            isValidating={isValidating.contact_number}
            onChange={(v) => handleInputChangeWithValidation("contact_number", v)}
          />

          <div>
            <Label htmlFor="cnic" className="font-semibold text-gray-700">CNIC *</Label>
            <Input
              id="cnic"
              value={formData.cnic || ""}
              onChange={(e) => handleInputChangeWithValidation("cnic", e.target.value)}
              placeholder="XXXXX-XXXXXXX-X"
              maxLength={15}
              className={`border-2 rounded-xl h-11 focus:border-blue-400 ${invalidFields.includes("cnic") || fieldErrors.cnic ? "border-red-500" : ""}`}
            />
            {invalidFields.includes("cnic") && <p className="text-xs text-red-500 mt-1 font-medium">CNIC is required</p>}
            {fieldErrors.cnic && (
              <p className="text-xs text-red-500 flex items-center gap-1 mt-1 font-medium italic">
                <AlertCircle className="h-3.5 w-3.5" />
                {fieldErrors.cnic}
              </p>
            )}
            {isValidating.cnic && (
              <p className="text-xs text-blue-500 flex items-center gap-1 mt-1 animate-pulse italic">
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                Checking CNIC availability...
              </p>
            )}
            {!fieldErrors.cnic && formData.cnic && !isValidating.cnic && (
              <p className="text-xs text-green-600 flex items-center gap-1 mt-1 font-medium">
                <CheckCircle className="h-3.5 w-3.5 text-green-500" />
                CNIC is valid and available
              </p>
            )}
          </div>

          <div>
            <Label htmlFor="marital_status" className="font-semibold text-gray-700">Marital Status</Label>
            <Select value={formData.marital_status || ""} onValueChange={(v) => onInputChange("marital_status", v)}>
              <SelectTrigger className={`border-2 rounded-xl h-11 focus:border-blue-400 ${invalidFields.includes("marital_status") ? "border-red-500" : ""}`}>
                <SelectValue placeholder="Select status" />
              </SelectTrigger>
              <SelectContent className="rounded-xl">
                {(formOptions?.marital_status && formOptions.marital_status.length > 0)
                  ? formOptions.marital_status.map((o: any) => (
                      <SelectItem key={o.value} value={o.value} className="py-2.5">{o.label}</SelectItem>
                    ))
                  : (
                    <>
                      <SelectItem value="single" className="py-2.5">Single</SelectItem>
                      <SelectItem value="married" className="py-2.5">Married</SelectItem>
                      <SelectItem value="divorced" className="py-2.5">Divorced</SelectItem>
                      <SelectItem value="widowed" className="py-2.5">Widowed</SelectItem>
                    </>
                  )}
              </SelectContent>
            </Select>
            {invalidFields.includes("marital_status") && <p className="text-xs text-red-500 mt-1 font-medium italic">Marital status is required</p>}
          </div>

          <div className="md:col-span-2">
            <Label htmlFor="email" className="font-semibold text-gray-700">Email Address *</Label>
            <Input
              id="email"
              type="email"
              value={formData.email || ""}
              onChange={(e) => handleInputChangeWithValidation("email", e.target.value)}
              className={`border-2 rounded-xl h-11 focus:border-blue-400 ${invalidFields.includes("email") || fieldErrors.email ? "border-red-500" : ""}`}
              placeholder="teacher@school.com"
            />
            {invalidFields.includes("email") && <p className="text-xs text-red-500 mt-1 font-medium">Email is required</p>}
            {fieldErrors.email && (
              <p className="text-xs text-red-500 flex items-center gap-1 mt-1 font-medium italic">
                <AlertCircle className="h-3.5 w-3.5" />
                {fieldErrors.email}
              </p>
            )}
            {isValidating.email && (
              <p className="text-xs text-blue-500 flex items-center gap-1 mt-1 animate-pulse italic">
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                Checking email...
              </p>
            )}
            {!fieldErrors.email && formData.email && !isValidating.email && (
              <p className="text-xs text-green-600 flex items-center gap-1 mt-1 font-medium">
                <CheckCircle className="h-3.5 w-3.5 text-green-500" />
                Email is available
              </p>
            )}
          </div>

          <div className="md:col-span-2">
            <Label htmlFor="current_address" className="font-semibold text-gray-700">Current Address *</Label>
            <Textarea
              id="current_address"
              value={formData.current_address || ""}
              onChange={(e) => onInputChange("current_address", e.target.value)}
              className={`border-2 rounded-2xl min-h-[100px] focus:border-blue-400 ${invalidFields.includes("current_address") ? "border-red-500" : ""}`}
              placeholder="Enter current address"
            />
            {invalidFields.includes("current_address") && <p className="text-xs text-red-500 mt-1 font-medium italic">Current address is required</p>}
          </div>

          <div className="md:col-span-2">
            <Label htmlFor="permanent_address" className="font-semibold text-gray-700">Permanent Address (Optional)</Label>
            <Textarea
              id="permanent_address"
              value={formData.permanent_address || ""}
              onChange={(e) => onInputChange("permanent_address", e.target.value)}
              placeholder="Enter permanent address (optional)"
              className="border-2 rounded-2xl min-h-[100px] focus:border-blue-400"
            />
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
