# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behaviour', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybehaviourrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_behaviour_records', to='users.organization'),
        ),
        migrations.AddField(
            model_name='monthlybehaviourrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_behaviour_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentbehaviourrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='users.organization'),
        ),
        migrations.AddField(
            model_name='studentbehaviourrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='studenteventparticipation',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='behaviour.studentbehaviourrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybehaviourrecord',
            unique_together={('student', 'month')},
        ),
    ]
