# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Role',
                'verbose_name_plural': 'Teacher Roles',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=teachers.models.teacher_photo_path)),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('cnic', models.CharField(max_length=15)),
                ('signature', models.TextField(blank=True, help_text='Base64 encoded signature image', null=True)),
                ('signature_updated_at', models.DateTimeField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('education_subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('education_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_position', models.CharField(blank=True, max_length=150, null=True)),
                ('experience_from_date', models.DateField(blank=True, null=True)),
                ('experience_to_date', models.DateField(blank=True, null=True)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('current_role_title', models.CharField(blank=True, max_length=150, null=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', help_text="Teacher's working shift", max_length=20)),
                ('current_subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('current_classes_taught', models.CharField(blank=True, max_length=200, null=True)),
                ('current_extra_responsibilities', models.TextField(blank=True, null=True)),
                ('role_start_date', models.DateField(blank=True, null=True)),
                ('is_currently_active', models.BooleanField(default=True)),
                ('teacher_id', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True)),
                ('biometric_id', models.CharField(blank=True, help_text='ZKTeco device user ID for auto-mapping', max_length=50, null=True)),
                ('save_status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('dynamic_data', models.JSONField(blank=True, default=dict, help_text='Stores extra dynamic form data', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Is this teacher a class teacher?')),
                ('is_teacher_assistant', models.BooleanField(default=False, help_text='Is this teacher an assistant teacher?')),
                ('class_teacher_grade', models.CharField(blank=True, help_text='Grade for class teacher assignment', max_length=50, null=True)),
                ('class_teacher_section', models.CharField(blank=True, help_text='Section for class teacher assignment', max_length=10, null=True)),
                ('classroom_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_classroom', models.OneToOneField(blank=True, help_text='LEGACY: Single classroom assignment (use assigned_classrooms instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_class_teacher', to='classes.classroom')),
                ('assigned_classrooms', models.ManyToManyField(blank=True, help_text='Classrooms assigned to this class teacher (can be multiple for both shifts)', related_name='class_teachers', to='classes.classroom')),
                ('assigned_coordinator', models.ForeignKey(blank=True, help_text='LEGACY: Single coordinator (use assigned_coordinators instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_assigned_teachers', to='coordinator.coordinator')),
                ('assigned_coordinators', models.ManyToManyField(blank=True, help_text='Coordinators assigned to this teacher based on grades/levels taught', related_name='assigned_teachers', to='coordinator.coordinator')),
                ('class_teacher_level', models.ForeignKey(blank=True, help_text='Level for class teacher assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='classes.level')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-date_created'],
            },
        ),
    ]
