# Generated by Django 5.2.12 on 2026-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
