# Generated by Django 5.2.12 on 2026-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_subject_teacher',
            field=models.BooleanField(default=False, help_text='Is this teacher a subject teacher?'),
        ),
    ]
