# Generated by Django 5.2.15 on 2026-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teachersubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience_subjects_classes_taught',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='previous_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
