# Generated by Django 5.2.15 on 2026-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_experience_subjects_classes_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
