# Generated by Django 5.2.13 on 2026-04-22 10:38

import coordinator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=coordinator.models.coordinator_photo_path)),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.CharField(max_length=15)),
                ('permanent_address', models.TextField()),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('total_experience_years', models.PositiveIntegerField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('both', 'Morning + Afternoon'), ('all', 'All Shifts')], default='both', help_text='Shift(s) this coordinator manages', max_length=20)),
                ('joining_date', models.DateField()),
                ('is_currently_active', models.BooleanField(default=True)),
                ('can_assign_class_teachers', models.BooleanField(default=True, help_text='Can this coordinator assign class teachers?')),
                ('signature', models.TextField(blank=True, help_text='Base64 encoded signature image', null=True)),
                ('signature_updated_at', models.DateTimeField(blank=True, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True)),
                ('biometric_id', models.CharField(blank=True, help_text='ZKTeco device user ID for auto-mapping', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_levels', models.ManyToManyField(blank=True, help_text='Levels managed by this coordinator when shift is both', related_name='assigned_coordinators', to='classes.level')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_set', to='classes.level')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['-created_at'],
            },
        ),
    ]
