# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinator', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='users.organization'),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_active_coordinator_email'),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cnic',), name='unique_active_coordinator_cnic'),
        ),
        migrations.AddConstraint(
            model_name='coordinator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_code',), name='unique_active_coordinator_employee_code'),
        ),
    ]
