# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
import principals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=principals.models.principal_photo_path)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='Pakistani', max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_address', models.TextField()),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(max_length=100)),
                ('degree_title', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('total_experience_years', models.PositiveIntegerField()),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_designation', models.CharField(blank=True, max_length=150, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('acting', 'Acting Principal')], default='principal', max_length=50)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('both', 'Both'), ('all', 'All Shifts')], default='morning', help_text="Principal's working shift", max_length=20)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('visiting', 'Visiting')], default='permanent', max_length=20)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('is_currently_active', models.BooleanField(default=True)),
                ('signature', models.TextField(blank=True, help_text='Base64 encoded signature image', null=True)),
                ('signature_updated_at', models.DateTimeField(blank=True, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True)),
                ('biometric_id', models.CharField(blank=True, help_text='ZKTeco device user ID for auto-mapping', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus')),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principals',
                'ordering': ['-created_at'],
            },
        ),
    ]
