# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principals', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='users.organization'),
        ),
        migrations.AddField(
            model_name='principal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('campus', 'shift'), name='unique_principal_per_campus_shift'),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_active_principal_email'),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cnic',), name='unique_active_principal_cnic'),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_code',), name='unique_active_principal_employee_code'),
        ),
    ]
