# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('timetable_type', models.CharField(choices=[('class', 'Class Timetable'), ('teacher', 'Teacher Timetable')], default='class', help_text='Type of timetable (class or teacher)', max_length=20)),
                ('name', models.CharField(help_text='Period name (e.g., Period 1, Break)', max_length=50)),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering for display')),
                ('days', models.JSONField(blank=True, default=list, help_text="Days this timing applies to (e.g., ['Monday', 'Tuesday']). Empty means all days.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift Timing',
                'verbose_name_plural': 'Shift Timings',
                'ordering': ['campus', 'shift', 'timetable_type', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name (e.g., Mathematics, English)', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Auto-generated subject code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Subject description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this subject currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Period start time')),
                ('end_time', models.TimeField(help_text='Period end time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break period?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Time Table',
                'verbose_name_plural': 'Teacher Time Tables',
                'ordering': ['teacher', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Period start time')),
                ('end_time', models.TimeField(help_text='Period end time')),
                ('is_break', models.BooleanField(default=False, help_text='Is this a break period?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(help_text='Classroom for this period', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetable_periods', to='classes.classroom')),
            ],
            options={
                'verbose_name': 'Class Time Table',
                'verbose_name_plural': 'Class Time Tables',
                'ordering': ['classroom', 'day', 'start_time'],
            },
        ),
    ]
