# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0002_initial'),
        ('teachers', '0002_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='users.organization'),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher assigned to this period', on_delete=django.db.models.deletion.CASCADE, related_name='class_teaching_periods', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='campus',
            field=models.ForeignKey(help_text='Campus this timing belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shift_timings', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='shifttiming',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_timings', to='users.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(help_text='Campus this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level this subject is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='classes.level'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.organization'),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='subject',
            field=models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='class_periods', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='classroom',
            field=models.ForeignKey(help_text='Classroom where teaching', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_teaching_periods', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='users.organization'),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='subject',
            field=models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_periods', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher for this period', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetable_periods', to='teachers.teacher'),
        ),
        migrations.AddConstraint(
            model_name='shifttiming',
            constraint=models.UniqueConstraint(fields=('campus', 'shift', 'timetable_type', 'name'), name='unique_shift_period_name'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'campus')},
        ),
        migrations.AddConstraint(
            model_name='classtimetable',
            constraint=models.UniqueConstraint(fields=('classroom', 'day', 'start_time'), name='unique_class_period'),
        ),
        migrations.AddConstraint(
            model_name='teachertimetable',
            constraint=models.UniqueConstraint(fields=('teacher', 'day', 'start_time'), name='unique_teacher_period'),
        ),
    ]
