# Generated by Django 6.0.4 on 2026-04-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0002_initial'),
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'campus', 'level')},
        ),
    ]
