# Generated by Django 5.2.13 on 2026-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('teacher', 'Teacher'), ('coordinator', 'Coordinator')], max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request Comment',
                'verbose_name_plural': 'Request Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('leave', 'Leave Request'), ('salary', 'Salary Issue'), ('facility', 'Facility Complaint'), ('resource', 'Resource Request'), ('student', 'Student Related'), ('admin', 'Administrative Issue'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending_principal', 'Pending Principal Approval'), ('approved', 'Approved'), ('pending_confirmation', 'Pending Teacher Confirmation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=10)),
                ('requires_principal_approval', models.BooleanField(default=False)),
                ('forwarding_note', models.TextField(blank=True, help_text="Coordinator's note when forwarding to principal", null=True)),
                ('approved_by', models.CharField(blank=True, help_text='coordinator or principal', max_length=20, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_confirmed', models.BooleanField(default=False)),
                ('teacher_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_satisfaction_note', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('coordinator_notes', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_principal_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Request/Complaint',
                'verbose_name_plural': 'Requests/Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending_principal', 'Pending Principal Approval'), ('approved', 'Approved'), ('pending_confirmation', 'Pending Teacher Confirmation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('pending_principal', 'Pending Principal Approval'), ('approved', 'Approved'), ('pending_confirmation', 'Pending Teacher Confirmation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_by', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
