# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinator', '0002_initial'),
        ('principals', '0002_initial'),
        ('requests', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_comments', to='users.organization'),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requests', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.organization'),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_requests', to='principals.principal'),
        ),
        migrations.AddField(
            model_name='requestcomplaint',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests.requestcomplaint'),
        ),
        migrations.AddField(
            model_name='requeststatushistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_status_histories', to='users.organization'),
        ),
        migrations.AddField(
            model_name='requeststatushistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.requestcomplaint'),
        ),
    ]
