# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.organization'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancebackfillpermission',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='attendancebackfillpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_backfill_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancebackfillpermission',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancebackfillpermission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backfill_permissions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeshifttiming',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_shift_timings', to='users.organization'),
        ),
        migrations.AddField(
            model_name='employeeshifttiming',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_timing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='classes.level'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='holiday_set', to='classes.level'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.organization'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendances', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_teacher_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='users.organization'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendances', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='users.organization'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_student_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekend',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weekends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekend',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekends', to='classes.level'),
        ),
        migrations.AddField(
            model_name='weekend',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekends', to='users.organization'),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zkteco_devices', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zkteco_devices', to='users.organization'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='attendance.zktecodevice'),
        ),
        migrations.AddField(
            model_name='zktecoemployeemapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zktecoemployeemapping',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='attendance.zktecodevice'),
        ),
        migrations.AddField(
            model_name='zktecoemployeemapping',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zkteco_mappings', to='users.organization'),
        ),
        migrations.AddField(
            model_name='zktecoemployeemapping',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_mappings', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='zktecoemployeemapping',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zkteco_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('classroom', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancebackfillpermission',
            unique_together={('classroom', 'date', 'granted_to')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['feature', 'action'], name='attendance__feature_cc634e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='attendance__entity__dc2b48_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='attendance__user_id_5d1716_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'attendance')},
        ),
        migrations.AddIndex(
            model_name='weekend',
            index=models.Index(fields=['date'], name='attendance__date_153ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='weekend',
            index=models.Index(fields=['level', 'date'], name='attendance__level_i_84f371_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weekend',
            unique_together={('date', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='zktecoemployeemapping',
            unique_together={('device', 'device_user_id')},
        ),
    ]
