# Generated by Django 5.2.14 on 2026-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('submit', 'Submit'), ('review', 'Review'), ('finalize', 'Finalize'), ('reopen', 'Reopen'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('unassign', 'Unassign')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='feature',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('student', 'Student'), ('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('principal', 'Principal'), ('classroom', 'Classroom'), ('grade', 'Grade'), ('level', 'Level'), ('campus', 'Campus'), ('user', 'User'), ('result', 'Result')], max_length=50),
        ),
    ]
