# Generated by Django 5.2.15 on 2026-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auditlog_is_recovered_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('submit', 'Submit'), ('review', 'Review'), ('finalize', 'Finalize'), ('reopen', 'Reopen'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('password_change', 'Password Change'), ('status_change', 'Status Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='feature',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('student', 'Student'), ('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('principal', 'Principal'), ('classroom', 'Classroom'), ('grade', 'Grade'), ('level', 'Level'), ('campus', 'Campus'), ('user', 'User'), ('result', 'Result'), ('transfer', 'Transfer')], max_length=50),
        ),
    ]
