# Generated by Django 5.2.14 on 2026-07-15 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_auditlog_action_alter_auditlog_feature'),
        ('classes', '0003_grade_order'),
        ('users', '0010_alter_rolepermission_permission_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['classroom', 'date', 'status'], name='attendance__classro_94d184_idx'),
        ),
    ]
