# Generated by Django 5.2.14 on 2026-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_excused_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('mark', 'Mark Attendance'), ('submit', 'Submit'), ('review', 'Review'), ('finalize', 'Finalize'), ('reopen', 'Reopen'), ('approve', 'Approve'), ('reject', 'Reject'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('password_change', 'Password Change'), ('status_change', 'Status Change')], max_length=50),
        ),
    ]
