# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_section', models.CharField(blank=True, max_length=10, null=True)),
                ('to_section', models.CharField(blank=True, max_length=10, null=True)),
                ('from_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this change.')),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeSkipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('from_section', models.CharField(blank=True, max_length=10, null=True)),
                ('to_section', models.CharField(blank=True, max_length=10, null=True)),
                ('from_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('to_shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text='Optional: destination shift (if different from current shift).', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending_own_coord', 'Pending Own Coordinator'), ('pending_other_coord', 'Pending Other Coordinator'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_own_coord', max_length=40)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this grade skip.')),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('old_id', models.CharField(max_length=50)),
                ('old_campus_code', models.CharField(max_length=10)),
                ('old_shift', models.CharField(max_length=1)),
                ('old_year', models.CharField(max_length=2)),
                ('new_id', models.CharField(max_length=50)),
                ('new_campus_code', models.CharField(max_length=10)),
                ('new_shift', models.CharField(max_length=1)),
                ('new_year', models.CharField(max_length=2)),
                ('immutable_suffix', models.CharField(max_length=20)),
                ('change_reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('to_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('status', models.CharField(choices=[('pending_own_coord', 'Pending Own Coordinator'), ('pending_other_coord', 'Pending Other Coordinator'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_own_coord', max_length=40)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this shift change.')),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('class', 'Class Transfer'), ('shift', 'Shift Transfer'), ('campus', 'Campus Transfer')], max_length=20)),
                ('transfer_id', models.PositiveIntegerField(help_text='Primary key of the underlying transfer object (ClassTransfer, ShiftTransfer, or TransferRequest).')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('coordinator_from', 'From Shift/Level Coordinator'), ('coordinator_to', 'To Shift/Level Coordinator'), ('principal', 'Principal')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('step_order', models.PositiveIntegerField(default=1, help_text='Logical order of this step within the workflow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transfer_type', 'transfer_id', 'step_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_category', models.CharField(blank=True, help_text='Optional category for this transfer (e.g. campus, shift_same_class).', max_length=50, null=True)),
                ('request_type', models.CharField(choices=[('student', 'Student Transfer'), ('teacher', 'Teacher Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('from_shift', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1)),
                ('to_shift', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('to_shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text='Destination shift on target campus.', max_length=20)),
                ('from_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_grade_name', models.CharField(blank=True, max_length=50, null=True)),
                ('from_section', models.CharField(blank=True, max_length=10, null=True)),
                ('to_section', models.CharField(blank=True, max_length=10, null=True)),
                ('skip_grade', models.BooleanField(default=False, help_text='If true, this transfer includes a grade skip to to_grade.')),
                ('status', models.CharField(choices=[('pending_from_coord', 'Pending From-Campus Coordinator'), ('pending_from_principal', 'Pending From-Campus Principal'), ('pending_to_principal', 'Pending To-Campus Principal'), ('pending_to_coord', 'Pending To-Campus Coordinator'), ('approved', 'Approved / Applied'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_from_coord', max_length=40)),
                ('reason', models.TextField()),
                ('requested_date', models.DateField(help_text='Effective date requested for this campus transfer.')),
                ('decline_reason', models.TextField(blank=True)),
                ('letter_generated_at', models.DateTimeField(blank=True, null=True)),
                ('letter_new_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('letter_from_campus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_campus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_from_class_label', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_class_label', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_from_principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_to_coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers_from', to='campus.campus')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from', to='classes.classroom')),
                ('from_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from_coord', to='coordinator.coordinator')),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from', to='classes.grade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
