# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0002_initial'),
        ('coordinator', '0002_initial'),
        ('students', '0002_initial'),
        ('teachers', '0002_initial'),
        ('transfers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campustransfer',
            name='from_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_from_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='initiated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_initiated', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers', to='users.organization'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='to_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers_to', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='to_classroom',
            field=models.ForeignKey(blank=True, help_text='Destination classroom after campus transfer (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='to_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to_coord', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='to_grade',
            field=models.ForeignKey(blank=True, help_text='Optional destination grade (used when skip_grade is enabled).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='to_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfers_to_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_reviewed', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='from_classroom',
            field=models.ForeignKey(blank=True, help_text='Original classroom for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_from', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='initiated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_initiated', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_transfers', to='users.organization'),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='principal',
            field=models.ForeignKey(blank=True, help_text='Optional final approver for class changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='to_classroom',
            field=models.ForeignKey(blank=True, help_text='Destination classroom after transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_transfers_to', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_skip_transfers', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='from_classroom',
            field=models.ForeignKey(blank=True, help_text='Original classroom for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_from', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='from_grade',
            field=models.ForeignKey(blank=True, help_text='Original grade for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_from', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='from_grade_coordinator',
            field=models.ForeignKey(blank=True, help_text="Coordinator for the student's current grade/level.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_from_grade', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='initiated_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_initiated', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_skip_transfers_org', to='users.organization'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='principal',
            field=models.ForeignKey(blank=True, help_text='Optional final approver for grade skip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_skip_transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='to_classroom',
            field=models.ForeignKey(blank=True, help_text='Destination classroom after grade skip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_to', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='to_grade',
            field=models.ForeignKey(blank=True, help_text='Destination grade after skip (must be exactly 1 grade ahead, e.g., Grade 1 → Grade 3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_to', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='to_grade_coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator for the target grade/level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfers_to_grade', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_histories', to='users.organization'),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_transfers', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='from_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_from', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='from_shift_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_from_shift', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_transfers_org', to='users.organization'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='requesting_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_initiated', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='to_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_to', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='to_shift_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfers_to_shift', to='coordinator.coordinator'),
        ),
        migrations.AddField(
            model_name='transferapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='from_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='users.organization'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='receiving_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requesting_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='shifttransfer',
            name='transfer_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_transfer', to='transfers.transferrequest'),
        ),
        migrations.AddField(
            model_name='idhistory',
            name='transfer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_changes', to='transfers.transferrequest'),
        ),
        migrations.AddField(
            model_name='gradeskiptransfer',
            name='transfer_request',
            field=models.OneToOneField(blank=True, help_text='Link to TransferRequest if student ID needs to be updated (e.g., shift/campus change).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_skip_transfer', to='transfers.transferrequest'),
        ),
        migrations.AddField(
            model_name='campustransfer',
            name='transfer_request',
            field=models.OneToOneField(blank=True, help_text='Auto-created TransferRequest used to perform the ID update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_transfer', to='transfers.transferrequest'),
        ),
        migrations.AddIndex(
            model_name='classtransfer',
            index=models.Index(fields=['status'], name='transfers_c_status_41c284_idx'),
        ),
        migrations.AddIndex(
            model_name='classtransfer',
            index=models.Index(fields=['student'], name='transfers_c_student_8964f8_idx'),
        ),
        migrations.AddIndex(
            model_name='transferapproval',
            index=models.Index(fields=['transfer_type', 'transfer_id'], name='transfers_t_transfe_91ca59_idx'),
        ),
        migrations.AddIndex(
            model_name='transferapproval',
            index=models.Index(fields=['role'], name='transfers_t_role_2daa50_idx'),
        ),
        migrations.AddIndex(
            model_name='transferapproval',
            index=models.Index(fields=['status'], name='transfers_t_status_665509_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status'], name='transfers_t_status_9a4f24_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['request_type'], name='transfers_t_request_5daa60_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['from_campus', 'to_campus'], name='transfers_t_from_ca_d92d62_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['requesting_principal', 'receiving_principal'], name='transfers_t_request_1883f9_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransfer',
            index=models.Index(fields=['status'], name='transfers_s_status_c5d848_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransfer',
            index=models.Index(fields=['student'], name='transfers_s_student_105125_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttransfer',
            index=models.Index(fields=['campus'], name='transfers_s_campus__a1e70c_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['entity_type'], name='transfers_i_entity__64bccd_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['old_id'], name='transfers_i_old_id_637d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['new_id'], name='transfers_i_new_id_bdb666_idx'),
        ),
        migrations.AddIndex(
            model_name='idhistory',
            index=models.Index(fields=['student', 'teacher'], name='transfers_i_student_4fdae5_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeskiptransfer',
            index=models.Index(fields=['status'], name='transfers_g_status_155a61_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeskiptransfer',
            index=models.Index(fields=['student'], name='transfers_g_student_f6d687_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeskiptransfer',
            index=models.Index(fields=['campus'], name='transfers_g_campus__ecbe1e_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeskiptransfer',
            index=models.Index(fields=['from_grade', 'to_grade'], name='transfers_g_from_gr_935f54_idx'),
        ),
        migrations.AddIndex(
            model_name='campustransfer',
            index=models.Index(fields=['status'], name='transfers_c_status_5c2e20_idx'),
        ),
        migrations.AddIndex(
            model_name='campustransfer',
            index=models.Index(fields=['student'], name='transfers_c_student_3549bf_idx'),
        ),
        migrations.AddIndex(
            model_name='campustransfer',
            index=models.Index(fields=['from_campus', 'to_campus'], name='transfers_c_from_ca_e093be_idx'),
        ),
    ]
