# Generated by Django 5.2.13 on 2026-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_photo', models.ImageField(blank=True, help_text='Campus photo (optional)', null=True, upload_to='campus/photos/')),
                ('campus_id', models.CharField(blank=True, help_text='Auto-generated if left blank: CITY-YEAR-POSTAL-CODE (e.g., KHI-25-75080-C01)', max_length=50)),
                ('campus_code', models.CharField(blank=True, max_length=50, null=True)),
                ('campus_name', models.CharField(blank=True, max_length=255)),
                ('campus_type', models.CharField(choices=[('main', 'Main'), ('branch', 'Branch')], default='main', max_length=20)),
                ('governing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction_language', models.CharField(blank=True, help_text='e.g. English, Urdu', max_length=255, null=True)),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('academic_year_end', models.DateField(blank=True, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address_full', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('campus_head_name', models.CharField(blank=True, max_length=255)),
                ('campus_head_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('campus_head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_capacity', models.PositiveIntegerField(default=0)),
                ('academic_year_start_month', models.CharField(blank=True, help_text="Month name e.g. 'April'", max_length=20, null=True)),
                ('academic_year_end_month', models.CharField(blank=True, help_text="Month name e.g. 'March'", max_length=20, null=True)),
                ('shift_available', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', max_length=20)),
                ('grades_available', models.TextField(blank=True, help_text='Comma separated e.g. Nursery, 1, 2, 3', null=True)),
                ('grades_offered', models.TextField(blank=True, help_text='Grades offered by campus', null=True)),
                ('total_rooms', models.PositiveIntegerField(default=0, editable=False)),
                ('total_classrooms', models.PositiveIntegerField(default=0)),
                ('total_staff_rooms', models.PositiveIntegerField(default=0)),
                ('has_computer_lab', models.BooleanField(default=False)),
                ('has_science_lab', models.BooleanField(default=False)),
                ('has_biology_lab', models.BooleanField(default=False)),
                ('has_chemistry_lab', models.BooleanField(default=False)),
                ('has_physics_lab', models.BooleanField(default=False)),
                ('library_available', models.BooleanField(blank=True, default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('internet_available', models.BooleanField(default=False)),
                ('teacher_transport', models.BooleanField(default=False)),
                ('student_transport', models.BooleanField(default=False, help_text='Student transport available')),
                ('canteen_facility', models.BooleanField(default=False)),
                ('meal_program', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='active', max_length=20)),
                ('sports_available', models.TextField(blank=True, help_text='If available, list sports e.g. Cricket, Football, Swimming', null=True)),
                ('grades_data', models.JSONField(blank=True, default=list, help_text='Structured grades with levels, grades, and classrooms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=False, help_text='If True, campus is in draft mode')),
            ],
        ),
    ]
