# Generated by Django 5.2.14 on 2026-06-03 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
        ('users', '0002_add_login_lockout_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'user', '-updated_at'], name='ai_chat_con_organiz_bf376f_idx'),
        ),
    ]
