# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_initial'),
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned the class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher for this classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_set', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users.organization'),
        ),
        migrations.AddField(
            model_name='grade',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_grades', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='grade',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.organization'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classes.grade'),
        ),
        migrations.AddField(
            model_name='level',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus this level belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='campus.campus'),
        ),
        migrations.AddField(
            model_name='level',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='users.organization'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level this grade belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_set', to='classes.level'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'section', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('campus', 'name', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('level', 'name', 'shift')},
        ),
    ]
