# Generated by Django 5.2.13 on 2026-04-22 10:38

import django.db.models.deletion
import django.utils.timezone
import users.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_org_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('org_admin', 'Organization Admin'), ('principal', 'Principal'), ('coordinator', 'Teacher Coordinator'), ('teacher', 'Teacher'), ('donor', 'Donor'), ('accounts_officer', 'Accountant'), ('admissions_counselor', 'Receptionist'), ('compliance_officer', 'Auditor'), ('student', 'Student')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('biometric_id', models.CharField(blank=True, help_text='User ID on Biometric Device', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('has_changed_default_password', models.BooleanField(default=False)),
                ('token_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
            },
            managers=[
                ('objects', users.managers.MultiTenantUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('max_users', models.PositiveIntegerField(default=50)),
                ('max_students', models.PositiveIntegerField(default=1000)),
                ('max_campuses', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled_features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'users_organization',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='users.organization'),
        ),
        migrations.CreateModel(
            name='PasswordChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('session_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change OTP',
                'verbose_name_plural': 'Password Change OTPs',
                'db_table': 'users_password_change_otp',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_users', models.PositiveIntegerField()),
                ('max_students', models.PositiveIntegerField()),
                ('max_campuses', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_student', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_user', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_enterprise', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'users_subscription_plan',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='users.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('org_admin', 'Organization Admin'), ('principal', 'Principal'), ('coordinator', 'Teacher Coordinator'), ('teacher', 'Teacher'), ('donor', 'Donor'), ('accounts_officer', 'Accountant'), ('admissions_counselor', 'Receptionist'), ('compliance_officer', 'Auditor'), ('student', 'Student')], max_length=20)),
                ('permission_codename', models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_students', 'View Students'), ('add_student', 'Add Student'), ('edit_student', 'Edit Student'), ('view_teachers', 'View Teachers'), ('add_teacher', 'Add Teacher'), ('edit_teacher', 'Edit Teacher'), ('view_campus', 'View Campus'), ('add_campus', 'Add Campus'), ('view_principals', 'View Principals'), ('add_principal', 'Add Principal'), ('edit_principal', 'Edit Principal'), ('view_coordinators', 'View Coordinators'), ('add_coordinator', 'Add Coordinator'), ('edit_coordinator', 'Edit Coordinator'), ('view_attendance', 'View Attendance'), ('mark_attendance', 'Mark Attendance'), ('approve_attendance', 'Approve Attendance'), ('view_results', 'View Results'), ('approve_results', 'Approve Results'), ('bulk_import_results', 'Bulk Import Results'), ('edit_results', 'Edit Results'), ('view_transfers', 'View Transfers'), ('view_timetable', 'View Timetable'), ('view_requests', 'View Requests'), ('view_promotions', 'View Promotions'), ('view_subjects', 'View Subjects'), ('view_grade_distribution_chart', 'View Grade Distribution Chart'), ('view_gender_distribution_chart', 'View Gender Distribution Chart'), ('view_mother_tongue_chart', 'View Mother Tongue Chart'), ('view_religion_chart', 'View Religion Chart'), ('view_enrollment_trend_chart', 'View Enrollment Trend Chart'), ('view_age_distribution_chart', 'View Age Distribution Chart'), ('view_weekly_attendance_chart', 'View Weekly Attendance Chart'), ('view_zakat_status_chart', 'View Zakat Status Chart'), ('view_house_ownership_chart', 'View House Ownership Chart'), ('view_total_students_kpi', 'View Total Students KPI'), ('view_total_teachers_kpi', 'View Total Teachers KPI'), ('view_teacher_student_ratio_kpi', 'View Teacher-Student Ratio KPI'), ('view_avg_attendance_kpi', 'View Average Attendance KPI'), ('view_fees', 'View Fees & Vouchers'), ('manage_fees', 'Manage Fees Collections'), ('manage_permissions', 'Manage Permissions'), ('manage_forms', 'Manage Forms')], max_length=100)),
                ('is_allowed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.organization')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'users_role_permission',
                'ordering': ['organization', 'role', 'permission_codename'],
                'unique_together': {('organization', 'role', 'permission_codename')},
            },
        ),
    ]
