# Generated by Django 5.2.14 on 2026-06-04 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_login_lockout_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('build', models.PositiveIntegerField()),
                ('release_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Version',
                'verbose_name_plural': 'System Versions',
                'db_table': 'users_system_version',
                'ordering': ['-created_at'],
            },
        ),
    ]
