# Generated by Django 5.2.14 on 2026-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_system_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='git_commit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
