# Generated by Django 5.2.14 on 2026-06-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_git_commit_to_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemversion',
            name='git_commit',
        ),
    ]
