# Generated by Django 5.2.14 on 2026-06-05 05:14
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_git_commit'),
    ]

    operations = [
    ]