# Generated by Django 5.2.14 on 2026-07-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0005_remove_git_commit_0008_merge_20260515_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission_codename',
            field=models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_students', 'View Students'), ('add_student', 'Add Student'), ('edit_student', 'Edit Student'), ('view_teachers', 'View Teachers'), ('add_teacher', 'Add Teacher'), ('edit_teacher', 'Edit Teacher'), ('view_campus', 'View Campus'), ('add_campus', 'Add Campus'), ('view_principals', 'View Principals'), ('add_principal', 'Add Principal'), ('edit_principal', 'Edit Principal'), ('view_coordinators', 'View Coordinators'), ('add_coordinator', 'Add Coordinator'), ('edit_coordinator', 'Edit Coordinator'), ('view_attendance', 'View Attendance'), ('mark_attendance', 'Mark Attendance'), ('approve_attendance', 'Approve Attendance'), ('view_results', 'View Results'), ('approve_results', 'Approve Results'), ('bulk_import_results', 'Bulk Import Results'), ('edit_results', 'Edit Results'), ('view_transfers', 'View Transfers'), ('view_timetable', 'View Timetable'), ('view_requests', 'View Requests'), ('view_promotions', 'View Promotions'), ('view_subjects', 'View Subjects'), ('view_grade_distribution_chart', 'View Grade Distribution Chart'), ('view_gender_distribution_chart', 'View Gender Distribution Chart'), ('view_mother_tongue_chart', 'View Mother Tongue Chart'), ('view_religion_chart', 'View Religion Chart'), ('view_enrollment_trend_chart', 'View Enrollment Trend Chart'), ('view_age_distribution_chart', 'View Age Distribution Chart'), ('view_weekly_attendance_chart', 'View Weekly Attendance Chart'), ('view_zakat_status_chart', 'View Zakat Status Chart'), ('view_house_ownership_chart', 'View House Ownership Chart'), ('view_network_performance_chart', 'View Network Performance Dashboard'), ('view_total_students_kpi', 'View Total Students KPI'), ('view_total_teachers_kpi', 'View Total Teachers KPI'), ('view_teacher_student_ratio_kpi', 'View Teacher-Student Ratio KPI'), ('view_avg_attendance_kpi', 'View Average Attendance KPI'), ('view_fees', 'View Fees & Vouchers'), ('manage_fees', 'Manage Fees Collections'), ('manage_permissions', 'Manage Permissions'), ('manage_forms', 'Manage Forms')], max_length=100),
        ),
    ]
