# Generated by Django 5.2.12 on 2026-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retestschedule',
            name='exam_type',
            field=models.CharField(choices=[('monthly', 'Monthly Test'), ('midterm', 'Mid Term'), ('final', 'Final Term')], max_length=20),
        ),
    ]
