name: Deploy School Management System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to server root
        run: |
          echo "Copying files to /var/www/School-Management-System..."
          cp -r ./* /var/www/School-Management-System/
          echo "Files copied successfully!"