name: Deploy School Management System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server Root
        run: |
          echo "Deploying School Management System..."
          sudo mkdir -p /var/www/School-Management-System
          sudo cp -r . /var/www/School-Management-System/
          sudo chown -R $USER:$USER /var/www/School-Management-System
          echo "Deployment Completed Successfully!"