name: Deploy School Management System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to Web Root
        run: |
          echo "Deploying School Management System files..."
          cp -r ./* /var/www/School-Management-System/
          echo "Deployment Completed Successfully!"